LINEAR REGRESSION

LIBRARY

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [2]:
pd.read_csv('_1Student-Performance-csv_T4qDx.csv')

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0                 7               99                        Yes            9   
1                 4               82                         No            4   
2                 8               51                        Yes            7   
3                 5               52                        Yes            5   
4                 7               75                         No            8   
...             ...              ...                        ...          ...   
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [3]:
df = pd.read_csv('_1Student-Performance-csv_T4qDx.csv')

In [4]:
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1               91.0  
1                                 2               65.0  
2                                 2               45.0  
3                                 2               36.0  
4                                 5               66.0

In [5]:
df.tail()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
9995              1               49                        Yes            4   
9996              7               64                        Yes            8   
9997              6               83                        Yes            8   
9998              9               97                        Yes            7   
9999              7               74                         No            8   

      Sample Question Papers Practiced  Performance Index  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0

In [6]:
df.describe()

Hours Studied  Previous Scores   Sleep Hours  \
count   10000.000000     10000.000000  10000.000000   
mean        4.992900        69.445700      6.530600   
std         2.589309        17.343152      1.695863   
min         1.000000        40.000000      4.000000   
25%         3.000000        54.000000      5.000000   
50%         5.000000        69.000000      7.000000   
75%         7.000000        85.000000      8.000000   
max         9.000000        99.000000      9.000000   

       Sample Question Papers Practiced  Performance Index  
count                      10000.000000       10000.000000  
mean                           4.583300          55.224800  
std                            2.867348          19.212558  
min                            0.000000          10.000000  
25%                            2.000000          40.000000  
50%                            5.000000          55.000000  
75%                            7.000000          71.000000  
max                            9.000000         100.000000

In [7]:
df.isnull()

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0             False            False                       False        False   
1             False            False                       False        False   
2             False            False                       False        False   
3             False            False                       False        False   
4             False            False                       False        False   
...             ...              ...                         ...          ...   
9995          False            False                       False        False   
9996          False            False                       False        False   
9997          False            False                       False        False   
9998          False            False                       False        False   
9999          False            False                       False        False   

      Sample Question Papers Practiced  Performance Index  
0                                False              False  
1                                False              False  
2                                False              False  
3                                False              False  
4                                False              False  
...                                ...                ...  
9995                             False              False  
9996                             False              False  
9997                             False              False  
9998                             False              False  
9999                             False              False  

[10000 rows x 6 columns]

In [8]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [10]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [11]:
#Extracurricular Activities   ------------------------> object
#Encoding -----------------------------> Label Encoding
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [12]:
df["Extracurricular Activities"]

0       Yes
1        No
2       Yes
3       Yes
4        No
       ... 
9995    Yes
9996    Yes
9997    Yes
9998    Yes
9999     No
Name: Extracurricular Activities, Length: 10000, dtype: object

In [17]:
le = LabelEncoder()
df["Extracurricular Activities"] = le.fit_transform(df["Extracurricular Activities"])

In [18]:
df

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  Performance Index  
0                                    1               91.0  
1                                    2               65.0  
2                                    2               45.0  
3                                    2               36.0  
4                                    5               66.0  
...                                ...                ...  
9995                                 2               23.0  
9996                                 5               58.0  
9997                                 5               74.0  
9998                                 0               95.0  
9999                                 1               64.0  

[10000 rows x 6 columns]

In [23]:
#CREATE X AND Y 
x = df[["Hours Studied","Previous Scores","Extracurricular Activities","Sleep Hours","Sample Question Papers Practiced"]]

In [24]:
x

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  
0                                    1  
1                                    2  
2                                    2  
3                                    2  
4                                    5  
...                                ...  
9995                                 2  
9996                                 5  
9997                                 5  
9998                                 0  
9999                                 1  

[10000 rows x 5 columns]

In [26]:
y = df[["Performance Index"]]

In [27]:
y

Performance Index
0                  91.0
1                  65.0
2                  45.0
3                  36.0
4                  66.0
...                 ...
9995               23.0
9996               58.0
9997               74.0
9998               95.0
9999               64.0

[10000 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train ,x_test ,y_train ,y_test = train_test_split(x,y,test_size=.2)

In [29]:
x_train

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
7771              3               54                           0            7   
9535              1               79                           0            4   
974               3               71                           0            6   
7194              5               79                           0            8   
7870              6               62                           1            5   
...             ...              ...                         ...          ...   
7261              7               46                           0            7   
5319              6               71                           0            4   
9298              3               40                           0            7   
2747              5               49                           0            7   
425               5               81                           0            6   

      Sample Question Papers Practiced  
7771                                 6  
9535                                 1  
974                                  8  
7194                                 0  
7870                                 0  
...                                ...  
7261                                 4  
5319                                 1  
9298                                 7  
2747                                 4  
425                                  5  

[8000 rows x 5 columns]

In [30]:
x_test

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
160               2               45                           1            4   
5995              8               46                           1            6   
8559              6               83                           0            4   
986               7               55                           0            4   
1489              3               75                           0            8   
...             ...              ...                         ...          ...   
1852              6               56                           0            7   
2212              4               73                           1            8   
5381              8               76                           0            9   
6435              4               72                           0            5   
307               3               86                           1            5   

      Sample Question Papers Practiced  
160                                  3  
5995                                 3  
8559                                 4  
986                                  7  
1489                                 1  
...                                ...  
1852                                 6  
2212                                 8  
5381                                 4  
6435                                 4  
307                                  9  

[2000 rows x 5 columns]

In [31]:
y_train

Performance Index
7771               32.0
9535               52.0
974                51.0
7194               64.0
7870               46.0
...                 ...
7261               37.0
5319               59.0
9298               21.0
2747               34.0
425                66.0

[8000 rows x 1 columns]

In [32]:
y_test

Performance Index
160                18.0
5995               41.0
8559               72.0
986                47.0
1489               55.0
...                 ...
1852               48.0
2212               59.0
5381               72.0
6435               56.0
307                69.0

[2000 rows x 1 columns]

In [36]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_train_scaled

array([[-0.77081546, -0.893449  , -0.99551008,  0.27951014,  0.48976017],
       [-1.54370808,  0.54865609, -0.99551008, -1.48118364, -1.25875883],
       [-0.77081546,  0.08718246, -0.99551008, -0.30738779,  1.18916777],
       ...,
       [-0.77081546, -1.70102785, -0.99551008,  0.27951014,  0.83946397],
       [ 0.00207715, -1.18187001, -0.99551008,  0.27951014, -0.20964743],
       [ 0.00207715,  0.6640245 , -0.99551008, -0.30738779,  0.14005637]])

In [38]:
x_test_scaled = scaler.fit_transform(x_test)
x_test_scaled

array([[-1.15060782, -1.3976869 ,  1.03459817, -1.53844353, -0.52422387],
       [ 1.16139718, -1.34010731,  1.03459817, -0.3355948 , -0.52422387],
       [ 0.39072885,  0.79033741, -0.96655883, -1.53844353, -0.17899906],
       ...,
       [ 1.16139718,  0.3872803 , -0.96655883,  1.46867831, -0.17899906],
       [-0.37993949,  0.15696195, -0.96655883, -0.93701917, -0.17899906],
       [-0.76527366,  0.96307618,  1.03459817, -0.93701917,  1.54712498]])

In [39]:
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [40]:
model = LinearRegression()
model.fit(x_train_scaled,y_train)

LinearRegression()

In [41]:
model.predict(x_test_scaled)

array([[20.8662049 ],
       [39.95586492],
       [70.48241359],
       ...,
       [71.5152418 ],
       [54.09634136],
       [66.99877126]])

In [45]:
y_pred = model.predict(x_test_scaled)

In [43]:
model.predict([[-1.15060782, -1.3976869 ,  1.03459817, -1.53844353, -0.52422387]])

array([[20.86620493]])

In [48]:
mean_squared_error(y_test,y_pred)

4.302576280497568

In [49]:
r2_score(y_test,y_pred)

0.9884738505213663

In [50]:
with open("_1student_lr_final_model.pkl",'wb') as file:
    pickle.dump((model,scaler,le),file)